* ww

*NOTE*: This package can be installed through forge [ https://github.com/malloc-nbytes/forge ].

*NOTE*: This project is a work in progress and may not function correctly.

*NOTE*: See [[./TODO.org][TODO]] for active features being worked on.

=ww= is a text editor similar to vim or nano but with a _very_ heavy Emacs influence (but nowhere near as customizable as it!).
It's controls are mostly default Emacs keybindings (see the help buffer in =ww= by doing =M-x help=).

Also, dependencies such as =ncurses= are not needed, just a =C= compiler and python for some pre-compile file generation.

** Dependencies

- A =C= compiler
- =python3=

** Compilation

*NOTE:* The =--prefix= option for =premake.py= is optional and is =/usr/local= by default.

#+begin_src bash
  cd src
  python3 premake.py --prefix=<prefix>
  make
  make install
#+end_src

** How to use

Invoke by doing =ww <filepath>= to start editing/creating a file.

To see the help buffer and to see the controls, either invoke =ww= with a directory (or nothing) instead of a file, or type =M-x help=.

You can also view a tutorial (wip) by invoking =M-x tutorial= and picking the chapter you are interested in.

