#include "default-config.h"

const char *g_default_config_str = "# Basic configuration file for ww,\n"
"# feel free to edit this file as you wish.\n"
"\n"
"# This file is written in 'qcl' which is a\n"
"# custom configuration language. It has similar\n"
"# syntax to rust.\n"
"\n"
"# See the repo: https://github.com/malloc-nbytes/qcl\n"
"\n"
"# Show ghost trailing whitespace characters\n"
"show-trails = true;\n"
"\n"
"# Use spaces instead of tabs\n"
"tab-mode = false;\n"
"\n"
"# The number of spaces when hitting <tab>\n"
"space-amt = '8';\n"
"\n"
"# The default compilation command\n"
"compile-command = 'make';\n"
"\n"
"# The way of copying the internal copy buffer\n"
"# to the system clipboard. The `%%s' is the data\n"
"# from the copy buffer.\n"
"to-clipboard = \"echo '%%s' | xclip -selection clipboard\";\n"
"\n"
"# Show the tilde character `~' on EOF lines.\n"
"empty-line-squiggles = true;\n"
"\n"
"# How to colorize highlighting in selection mode.\n"
"# Valid options are:\n"
"#   YELLOW, GREEN, BRIGHT_GREEN, GRAY, RED, BLUE, MAGENTA, ORANGE\n"
"#   WHITE, BLACK, CYAN, PINK, BRIGHT_PINK, PURPLE, BRIGHT_PURPLE, BROWN.\n"
"# Valid effects are:\n"
"#  UNDERLINE, BOLD, ITALIC, DIM, INVERT, RESET.\n"
"# You can mix-and-match them such as:\n"
"#  selection-highlight = 'YELLOW INVERT BOLD'.\n"
"selection-highlight = 'INVERT';\n";
