#include "default-config.h"

const char *g_default_config_str = "# Basic configuration file for ww,\n"
"# feel free to edit this file as you wish.\n"
"\n"
"# This file is written in 'qcl' which is a\n"
"# custom configuration language.\n"
"\n"
"# See the repo: https://github.com/malloc-nbytes/qcl\n"
"\n"
"wayland = $\"WAYLAND_DISPLAY\";\n"
"\n"
"# Show ghost trailing whitespace characters\n"
"show-trails = true;\n"
"\n"
"# Use spaces instead of tabs\n"
"tab-mode = false;\n"
"\n"
"# The number of spaces when hitting <tab>\n"
"space-amt = '8';\n"
"\n"
"# The default compilation command\n"
"compile-command = 'make';\n"
"\n"
"# The way of copying the internal copy buffer\n"
"# to the system clipboard. The `%%s' is the data\n"
"# from the copy buffer.\n"
"if !wayland: to-clipboard = \"echo -E '%%s' | xclip -selection clipboard\";\n"
"else         to-clipboard = \"echo -E '%%s' | wl-copy\";\n"
"\n"
"# Show the tilde character `~' on EOF lines.\n"
"empty-line-squiggles = true;\n"
"\n"
"# How to colorize highlighting in selection mode.\n"
"#\n"
"# Valid options are:\n"
"#   yellow, green, bright_green, gray, red, blue, magenta, orange\n"
"#   white, black, cyan, pink, bright_pink, purple, bright_purple, brown.\n"
"#\n"
"# Valid effects are:\n"
"#  underline, bold, italic, dim, invert, reset.\n"
"#\n"
"# You can mix-and-match them such as:\n"
"#  selection-highlight = 'yellow invert bold'.\n"
"#\n"
"selection-highlight = 'invert';\n"
"\n"
"# The colors when highlighting matches.\n"
"search-highlight = 'invert dim yellow';\n"
"\n"
"# The colors when highlighting the match under the cursor.\n"
"search-highlight-exact = 'invert bold orange';\n"
"\n"
"# The color to use when highlighting something in\n"
"# an autocomplete menu in `find-file', 'switch-buffer', etc.\n"
"menu-highlight = 'yellow bold invert';\n"
"\n"
"# Which buffers to open when `ww' is called on a directory\n"
"# or with no filepath provided at all. If this variable is\n"
"# undefined, invalid buffers are given, or it is `= ['']', it defaults to `ww-help'.\n"
"# Some valid options are:\n"
"#   ww-help, ww-calc\n"
"initial-buffers = ['ww-help'];\n";
