#!/usr/bin/env python3

import subprocess

template = '''#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

// NOTE: this file was generated by premake.py

#define VERSION "premake_VERSION"

#define COMPILER "premake_COMPILER"

#endif // CONFIG_H_INCLUDED'''

def info(msg):
    print('[premake]:', msg)

def make_compiler():
    info('reading compiler at /bin/cc')
    cc_path = '/bin/cc'
    try:
        result = subprocess.run([cc_path, "--version"], capture_output=True, text=True, check=True)
        return result.stdout.split('\n')[0]
    except FileNotFoundError:
        print(f"Compiler not found at {cc_path}")
    except subprocess.CalledProcessError as e:
        print(f"Error running compiler: {e}")

def make_body():
    info('making body')
    return template

def make_version():
    info('making version')
    version = None
    with open('../VERSION', 'r') as f:
        version = f.read().strip()
    assert version is not None
    return version

if __name__ == '__main__':
    cc       = make_compiler()
    version  = make_version()
    body_ver = 

    info('Writing include/config.h')

    with open('include/config.h', 'w', encoding='utf-8') as f:
        f.write('#ifndef CONFIG_H_INCLUDED\n')
        f.write('#define CONFIG_H_INCLUDED\n')
        f.write('\n')

    info('Done')
